# Generated by Django 4.0.5 on 2022-06-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentmodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='parent',
        ),
    ]
