# Generated by Django 4.0.5 on 2022-06-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_commentmodel_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='name',
            new_name='author',
        ),
    ]
