# Generated by Django 4.0.5 on 2022-06-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_name_commentmodel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
